version: "2.1"

services:
  grafana:
    image: grafana/grafana:6.7.2
    restart: on-failure
    volumes:
      - ./provisioning/grafana/:/etc/grafana/provisioning/
      # Grant admin rights to anon user
      - ./provisioning/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_USER: 1
      GF_SECURITY_ADMIN_PASSWORD: 1
      GF_SECURITY_DISABLE_GRAVATAR: "true"

      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: db:3306
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: password

      GF_SESSION_PROVIDER: mysql
      GF_SESSION_PROVIDER_CONFIG: grafana:password@tcp(db:3306)/grafana?allowNativePasswords=true

      GF_DATABASE_MAX_OPEN_CONN: 100

      GF_AUTH_ANONYMOUS_ENABLED: "true"

    ports:
      - 80:3000/tcp
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.6
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: password
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
    ports:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    volumes:
      - grafana-settings:/var/lib/mysql

  set_default_dashboard:
    image: arey/mysql-client
    restart: on-failure
    command: -h db -u grafana -ppassword -D grafana -e "REPLACE INTO preferences(id,org_id,home_dashboard_id,team_id) VALUES(1,1,1,0);"
    depends_on:
      db:
        condition: service_healthy

  influxdb:
    image: influxdb:1.8.0-alpine
    restart: on-failure
    expose:
      - 8086
    container_name: influxdb
    volumes:
      - sensors-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: sensors
      INFLUXDB_READ_USER: influx
      INFLUXDB_READ_PASSWORD: influx

volumes:
  grafana-settings:
  sensors-data:
